### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by byn17** [shogo4405/HaishinKit.dart#17]
### Describe the bug

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:0.10.2.
     Required by:
         project :app > project :haishin_kit
      > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:0.10.2.
         > Could not get resource 'https://jitpack.io/com/github/shogo4405/HaishinKit~kt/haishinkit/0.10.2/haishinkit-0.10.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/shogo4405/HaishinKit~kt/haishinkit/0.10.2/haishinkit-0.10.2.pom'. Received status code 521 from server: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### To Reproduce

1. flutter run

### Expected behavior

1. flutter run

### Version

0.9.2

### Smartphone info.

- Android

**Comment by shogo4405** [comment]
It seems that jitpack.io was down. Now you can!
