### ISSUE TITLE
Adobe authentication for rtmp not working on Android side

### ISSUE THREAD

**Issue by bypass112** [shogo4405/HaishinKit.dart#27]
### Describe the bug

Hello, I've been trying to connect to an rtmp publish server which requires authentification.
On my dart side I'm using 
```
RtmpConnection connection = await RtmpConnection.create();
connection.eventChannel.receiveBroadcastStream().listen((event) {
      printDebug("EVENT " + event.toString());
}
```
to read what are the auth messages that the server responds with.
iOS devices works fine and can publish a mic stream with the following messages:
```
flutter: EVENT {data: {level: error, code: NetConnection.Connect.Rejected, description: [ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ] : }, type: rtmpStatus}
flutter: EVENT {type: rtmpStatus, data: {description: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=user&salt=XXXX==&challenge=XXXX==&opaque=XXXX==, level: error, code: NetConnection.Connect.Rejected}}
flutter: EVENT {data: {data: [null], description: Connection succeeded, objectEncoding: 0.0, clientid: 1.0, level: status, code: NetConnection.Connect.Success}, type: rtmpStatus}
flutter: EVENT {type: rtmpStatus, data: {code: NetStream.Publish.Start, description: , clientid: 1.0, level: status, details: /streams.mount123}}
flutter: EVENT {data: null, type: rtmpStatus}
flutter: EVENT {type: rtmpStatus, data: {details: /streams.mount123, description: , level: status, code: NetStream.Publish.Start, clientid: 1.0}}
```
On Android side I'm not able to connect via adobe auth to the streaming server, I'm geting the following messages:
```
I/flutter (28417): EVENT {data: {code: NetConnection.Connect.Rejected, level: error, description: [ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ] : }, type: rtmpStatus}
I/flutter (28417): EVENT {data: {code: NetConnection.Connect.Rejected, level: error, description: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=user&salt=XXXX==&challenge=XXXX==&opaque=XXXX==}, type: rtmpStatus}
D/TrafficStats(28417): tagSocket(6) with statsTag=0xffffffff, statsUid=-1
I/flutter (28417): EVENT {data: {code: NetConnection.Connect.Closed, level: status}, type: rtmpStatus}
```
From what I've seen on Android side, the [connection.close()](https://github.com/shogo4405/HaishinKit.kt/blob/2ce69965eba61677e0e205c302e951a39cdcf465/haishinkit/src/main/java/com/haishinkit/rtmp/RtmpAuthenticator.kt#LL52C33-L52C33) is always called before a new connect attempt when the server asks for user and password, but on iOS the connection close is called only when[ one of the user and password field](https://github.com/shogo4405/HaishinKit.swift/blob/52ad7d6ad488734b61eb438894dd591baaf522df/Sources/RTMP/RTMPConnection.swift#L395) are empty. Is this where the issue originates?
Can you please help me with this please? I'm not sure on what I should begin looking into on the Android side.

### To Reproduce

1. Use the example project
2. For [line 138 ](https://github.com/shogo4405/HaishinKit.dart/blob/60ef32a2ee84a4ece135944cd466ec5e89619cda/example/lib/main.dart#LL138C14-L138C14) use ` _connection?.connect("rtmp://user:password@url/live");` in order to have user and password for the native layer to push forward.

### Expected behavior

Both Android and iOS devices should connect and publish to the rtmp adobe auth server.

### Version

haishin_kit: ^0.9.4

### Smartphone info.

- Any Android device or emulator
- Any iOS device, or simulator (on simulator the connection occurs but it won't stream any data from the mic)

**Comment by bypass112** [comment]
Ok I think I found out where the issue originates from.
I've been running the [HaishinKit.kt](https://github.com/shogo4405/HaishinKit.kt) project on my machine and it seems the issue originates from that project, to be more specific it seem that `val command = createAuthQuery(uri)` is adding unnecesary parameters at [line 76](https://github.com/shogo4405/HaishinKit.kt/blob/2ce69965eba61677e0e205c302e951a39cdcf465/haishinkit/src/main/java/com/haishinkit/rtmp/RtmpAuthenticator.kt#LL76C17-L76C17).
For example if in createAuthCommand method the uri comes as **rtmp://user:pass@address/live/?authmod=adobe&user=user**, val command will look like **rtmp://user:pass@address/live/?authmod=adobe&user=user/&authmod=adobe&user=user**.
In order to realize a proper connection to the rtmp adobe auth server I've just replaced
`val command = createAuthQuery(uri)`
with
`val command = uri.toString()`
So now the authentification command is properly composed and send to the server using **createAuthCommand** and the connection is established.
Although this solves my issue, I'm not sure if this is a proper solution for all cases, can you please advise on this?

**Comment by shogo4405** [comment]
It is likely because the code assumes that there is no trailing slash ("/") at the end. Could you please confirm if the following format without a slash works for you: rtmp://user:pass@address/live?

I realized that even in the library layer, it is necessary to consider cases where a trailing slash is present and cases where it is not. It's important to handle both scenarios to ensure proper functionality and compatibility with different URL formats.

**Comment by bypass112** [comment]
Hello I've used

```
if (!description.contains("?")) return uri.toString()
if (uri.rawUserInfo == null) return uri.toString()
val uri2 = URI(uri.toString().substring(0, uri.toString().lastIndexOf('/')) + "?")
val command = createAuthQuery(uri2)
```
in the **createAuthCommand** method to remove the **/?authmod=adobe&user=user** part from the original uri and create the URI format that you asked for and I can confirm that **createAuthQuery** method now works as intended and I can connect to the server.
Unfortunatelly I had to test it this way because Idon't have access to the server in order to not modify the URI on the frontend for this.

**Comment by shogo4405** [comment]
OK. Could you provide a pull request for the Android side? If you can, I will test it and release it.

**Comment by bypass112** [comment]
Hello.
I've made the pull request with the necessary changes. Please let me know if there is anything else needed for modifications.

**Comment by shogo4405** [comment]
Thank you very much. I have updated Android for better usability. Please try using this branch: https://github.com/shogo4405/HaishinKit.dart/tree/feature/adobe-auth

**Comment by bypass112** [comment]
Thank you so much for the help! Especially for your quick responses!
I'm sorry, I can't build the Flutter project anymore.
I'm getting:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:main-f2a055f138-1.
     Required by:
         project :app > project :haishin_kit
      > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:main-f2a055f138-1.
         > inconsistent module metadata found. Descriptor: com.github.shogo4405.HaishinKit~kt:haishinkit:main-SNAPSHOT Errors: bad version: expected='main-f2a055f138-1' found='main-SNAPSHOT'
      > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:main-f2a055f138-1.
         > inconsistent module metadata found. Descriptor: com.github.shogo4405.HaishinKit~kt:haishinkit:main-SNAPSHOT Errors: bad version: expected='main-f2a055f138-1' found='main-SNAPSHOT'
```
I've run **flutter clean** and **flutter pub cache clean** and the same error occurs.
I've also modified the dependency on my local pub cache folder based on [your commit](https://github.com/shogo4405/HaishinKit.dart/commit/567e316cb7118b47c1c33e1ec445ad3386af1236) from main-f2a055f138-1 to main-SNAPSHOT to see what happens and now I'm getting a different error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:main-SNAPSHOT.
     Required by:
         project :app > project :haishin_kit
      > Could not resolve com.github.shogo4405.HaishinKit~kt:haishinkit:main-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/shogo4405/HaishinKit~kt/haishinkit/main-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://jitpack.io/com/github/shogo4405/HaishinKit~kt/haishinkit/main-SNAPSHOT/maven-metadata.xml'.
               > Read timed out
```
Maybe it needs to be link to another build, like it was before to 0.11.0? I'm not sure what's going on now...

**Comment by shogo4405** [comment]
Thank you feedback. I have rebuilt it. It works for me. https://github.com/shogo4405/HaishinKit.dart/commit/1d2dd000d3661583b9d0b388dd6b7192c6852300

**Comment by shogo4405** [comment]
Thank you for the information about the Java version in Flutter. I've learned from it. I will try reverting to Java 1.8 as you suggested. After testing, I will release it. Please wait for a while. Thank you.

**Comment by shogo4405** [comment]
Hi. Thank you for contribution. I release HaishinKit.kt 0.11.1. And updated HaishinKit.dart ce25ae7.
