### ISSUE TITLE
Adding VideoEffect in RTMPStreamHandler does not take effect

### ISSUE THREAD

**Issue by tpc707494** [shogo4405/HaishinKit.dart#33]
### Describe the bug

The breakpoint will be entered, but has no effect

### To Reproduce

instance?.registerVideoEffect(MonochromeEffect())

final class MonochromeEffect: VideoEffect {
 let filter: CIFilter? = CIFilter(name: "CIColorMonochrome")

 override func execute(_ image: CIImage, info: CMSampleBuffer?) -> CIImage {
    guard let filter: CIFilter = filter else {
        return image
    }
    filter.setValue(image, forKey: "inputImage")
    filter.setValue(CIColor(red: 0.75, green: 0.75, blue: 0.75), forKey: "inputColor")
    filter.setValue(1.0, forKey: "inputIntensity")
    return filter.outputImage!
 }
}

### Expected behavior

image has grayscale

### Version

fork Version

**Comment by shogo4405** [comment]
I'm not sure. I cannot provide support for the parts that you have customized yourself and are not functioning. If it's not possible, let's give up.
