### ISSUE TITLE
registerTexture may not update the size of the texture on iOS

### ISSUE THREAD

**Issue by SimonWang9610** [shogo4405/HaishinKit.dart#45]
### Describe the bug

When invoking `RtmpStream#registerTexture` on iOS, it may create multiple `NetStreamDrawableTexture`.

As a result, it may show a black screen when previewing the camera video, as the texture has zero media size.

For example, to preview the camera correctly, we have to:
1) `registerTexture` to send the texture id back to the dart side
2) `registerTexture` with the media size to set the correct screen size for this texture.

However, if doing the two steps as the following:
```dart
mixin LiveStreamTextureMixin on LiveStreamConnectionManager {
  int? _textureId;
  Size? _previousSize;

  int? get textureId => _textureId;

  Future<int?> registerTexture({Size? size}) async {
    if (_stream == null) return null;

    _textureId ??= await _stream!.registerTexture({});

    if (size != null && _previousSize != size) {
       final textureId = await _stream!.registerTexture({
         "width": size.width,
         "height": size.height,
       });

      if (textureId != null && _textureId != textureId) {
         _textureId = textureId;
       }

       _previousSize = size;
    }

    return _textureId;
  }
```
The second invocation of `registerTexture("width":..)` may create a new `NetStreamDrawableTexture` instead of setting the size for the texture (previously created by the first invocation).

The main reason is because it is an async task when attaching the stream to a texture:
<img width="837" alt="image" src="https://github.com/shogo4405/HaishinKit.dart/assets/55259373/c3ff9168-5972-4d62-bbd2-d52e2c24fa58">
<img width="508" alt="image" src="https://github.com/shogo4405/HaishinKit.dart/assets/55259373/b8b8c6a8-3335-4833-853b-c2b4331f3e37">
Consequently, the second invocation may go to the branch: `instance?.mixer.drawable == nil` and then try to create a new texture, instead of setting a media size for a texture as we expected.

### To Reproduce

Use the below code to register textures:
```dart
mixin LiveStreamTextureMixin on LiveStreamConnectionManager {
  int? _textureId;
  Size? _previousSize;

  int? get textureId => _textureId;

  Future<int?> registerTexture({Size? size}) async {
    if (_stream == null) return null;

    _textureId ??= await _stream!.registerTexture({});

    if (size != null && _previousSize != size) {
       final textureId = await _stream!.registerTexture({
         "width": size.width,
         "height": size.height,
       });

      if (textureId != null && _textureId != textureId) {
         _textureId = textureId;
       }

       _previousSize = size;
    }

    return _textureId;
  }
```
The camera preview may show a black screen, depending on whether the texture has a valid media size.

If calling `registerTexture({Size? size})` continuously, it has a high chance of having a black screen.

### Expected behavior

1. The first invocation of `registerTexture` should register the texture and attach it to the stream synchronously
2. The second invocation of `RegisterTextture` should set the media size for the previously created texture correctly.

### Version

HaishinKit.dart: v0.11.2
Flutter: v3.10.5

### Smartphone info.

- iPhone 13 mini (iOS 16.1.2)

### Additional context

Is it necessary to attach a texture to the stream asynchronously?

In my forked version, I split the logic of registering the texture into 3 different methods:
1. `registerTexture`: only register a texture for Flutter
2. `updateTextureSize`: only set the media size for the texture attached to the net stream. if no attachment, just return nil.
3. `unregisterTexture`: to unregister the texture from the flutter registry (no need for Android, but recommended for iOS)

By doing so, we could ensure we are never creating a new texture and that the media size could be updated correctly.

However, the issue is not solved completely, as we still cannot predict exactly what time the texture has been attached to the net stream.

Therefore, I suggest creating the above three methods to make them more specific and then attaching a texture to the net stream synchronously. If it makes sense, I will create a PR.

**Comment by shogo4405** [comment]
Thank you for the report. I have limited knowledge of Flutter, and I'm not sure about the correct solution. If you could submit a pull request (PR), I would appreciate it, and I'll use it as a reference.
