### ISSUE TITLE
Unable to stream from android

### ISSUE THREAD

**Issue by waheed45103** [shogo4405/HaishinKit.dart#46]
### Describe the bug

When I call  _connection?.connect(
                  "rtmp://a.rtmp.youtube.com/live2/$token");
 
The first response in listener is: 'NetConnection.Connect.Success' and within a second receive "NetConnection.Connect.Closed"

### To Reproduce

Call the function: _connection?.connect(
                  "rtmp://a.rtmp.youtube.com/live2/$token"); from android

### Expected behavior

Start Livestreaming 

### Version

haishin_kit: ^0.11.2

**Comment by shogo4405** [comment]
I think it should be like this.
```
_connection?.connect("rtmp://a.rtmp.youtube.com/live2")
_stream.publish(“$token”)
```
