### ISSUE TITLE
You have some porblems with plugin implementation

### ISSUE THREAD

**Issue by Hellomik2002** [shogo4405/HaishinKit.dart#55]
### Describe the bug

You pass some wrong arguments

```
[ERROR:flutter/shell/common/shell.cc(1038)] The 'com.haishinkit.eventchannel/12929595648' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
```

### To Reproduce

Just launch it on Iphone

### Expected behavior

It should be parsable

### Version

0.13.0

**Comment by Hellomik2002** [comment]
ASObjectUtil.removeEmpty fucntion don't clean optional and ["type": Optional("rtmpStatus"), "data": Optional(["level": Optional("status"), "description": Optional("Connection succeeded."), "code": Optional("NetConnection.Connect.Success"), "objectEncoding": Optional(0.0)])] object cause error

**Comment by Hellomik2002** [comment]
Sorry I didn't slept few days

<img width="1205" alt="Screenshot 2024-03-28 at 8 22 48 AM" src="https://github.com/shogo4405/HaishinKit.dart/assets/30003495/71e53db5-7cc2-402e-b55b-66e05816c5bd">

**Comment by shogo4405** [comment]
It's not reproducing. It says to execute it on the main thread. Would it not be improved by changing it like this?

```
    @objc
    private func handler(_ notification: Notification) {
        let event = Event.from(notification)
        var map: [String: Any?] = [:]
        map["type"] = event.type.rawValue
        map["data"] = ASObjectUtil.removeEmpty(event.data)
        DispatchQueue.main.async {
             self.eventSink?(map)
        }
    }
```

**Comment by Hellomik2002** [comment]
I tried and now my main thread  crashing and app can not be builded, Try use breakpoint and launch in real device (Iphone 14 pro, IOS version 17.4.1) it could happen because Dart can parse nil from Swift but can not parse Optional<>, because it is special object in Swift, maybe let's parse object to json string and send it as string do Dart side code ? 

I determined that it wasn't my main error, but some messages can not be sent because parse wrong. 
<img width="611" alt="Screenshot 2024-03-28 at 11 44 49 PM" src="https://github.com/shogo4405/HaishinKit.dart/assets/30003495/6266e305-7267-41b9-a2a5-2d0fdb5ea4c7">
