### ISSUE TITLE
Why after disposing streams mobile app freezed for 5-10 seconds ?

### ISSUE THREAD

**Issue by Hellomik2002** [shogo4405/HaishinKit.dart#57]
### Describe the bug

I start the stream, but It works fine but when I stop stream and dispose it I can do nothing with app during 5-10 seconds

### To Reproduce

Launch example And dispose it(with stoping rtmp connection and stream)

### Expected behavior

Close it in another stream 

### Version

0.13.0

**Comment by shogo4405** [comment]
dispose is a method for disposing of instances, so there is a cost to restart. Please try close instead.
