### ISSUE TITLE
StreamViewTexture height and steramview resolution

### ISSUE THREAD

**Issue by ting28418** [shogo4405/HaishinKit.dart#58]
### Describe the bug

Can't adjust StreamViewTexture to show full screen camera.

### To Reproduce

If changes like  Future<void> _updatePlatformState(BoxConstraints constraints) async {
    widget.netStream?.updateTextureSize({
      "width": constraints.maxWidth,
      "height": constraints.maxHeight/3,
    }); show full screen of view but resolution was too bad show object taller and see unclear

### Expected behavior

Want to know how to modify to show texture with full screen and high resolution to see user clearly

### Version

Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ba39319843 (3 months ago) • 2024-03-07 15:22:21 -0600
Engine • revision 2e4ba9c6fb
Tools • Dart 3.3.1 • DevTools 2.31.1

### Smartphone info.

Huawei nova 3i

**Comment by shogo4405** [comment]
I understand that it didn't work well. However, I didn't understand what the expected result was. You mentioned that it is not high resolution, but what did you look at and how did you determine that?

**Comment by ting28418** [comment]
> I understand that it didn't work well. However, I didn't understand what the expected result was. You mentioned that it is not high resolution, but what did you look at and how did you determine that?

Sorry for inconvenience, We want to show StreamViewTexture with full screen ,from the example code show StreamViewTexture show at the center of phone manage height but not work how can we do to show full screen

**Comment by shogo4405** [comment]
I don't understand the question. I think our definitions of "full screen" might be different. I need you to show the code you wrote and provide details on the results you got.

widget.netStream?.updateTextureSize({
"width": constraints.maxWidth,
"height": constraints.maxHeight/3,
})

With this code, it seems like `constraints.maxHeight / 3` specifies one-third of the screen size, so it appears that the specification is not as intended.

**Comment by ting28418** [comment]
``import 'package:flutter/material.dart';
import 'package:haishin_kit/stream.dart';

class StreamViewTexture extends StatefulWidget {
  const StreamViewTexture(this.netStream, {Key? key}) : super(key: key);

  final Stream? netStream;

  @override
  State<StatefulWidget> createState() => _StreamViewTextureState();
}

class _StreamViewTextureState extends State<StreamViewTexture> {
  int? _textureId;

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    int? textureId = await widget.netStream?.registerTexture({});
    setState(() {
      _textureId = textureId;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_textureId == null) {
      return Container(
        color: Colors.black,
      );
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        _updatePlatformState(constraints);
        return Texture(textureId: _textureId!);
      },
    );
  }

  Future<void> _updatePlatformState(BoxConstraints constraints) async {
    widget.netStream?.updateTextureSize({
      "width": constraints.maxWidth,
      "height": constraints.maxHeight,
    });
  }
}

Result was attach pic (result1.jpeg) 
![result1](https://github.com/shogo4405/HaishinKit.dart/assets/110028664/f0c7edbf-6372-4538-84d5-07ac4296d66e)


import 'package:flutter/material.dart';
import 'package:haishin_kit/stream.dart';

class StreamViewTexture extends StatefulWidget {
  const StreamViewTexture(this.netStream, {Key? key}) : super(key: key);

  final Stream? netStream;

  @override
  State<StatefulWidget> createState() => _StreamViewTextureState();
}

class _StreamViewTextureState extends State<StreamViewTexture> {
  int? _textureId;

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    int? textureId = await widget.netStream?.registerTexture({});
    setState(() {
      _textureId = textureId;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_textureId == null) {
      return Container(
        color: Colors.black,
      );
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        _updatePlatformState(constraints);
        return Texture(textureId: _textureId!);
      },
    );
  }

  Future<void> _updatePlatformState(BoxConstraints constraints) async {
    widget.netStream?.updateTextureSize({
      "width": constraints.maxWidth,
      "height": constraints.maxHeight/3,
    });
  }
}
Result2 was attach pic (result2
![result2](https://github.com/shogo4405/HaishinKit.dart/assets/110028664/162de39b-fc77-423e-bdc8-1b571c485ed6)
.jpeg) 

How to show streamviewtexture full screen of phone and clear resolution here is ui widget 


 body: Center(
          child: _stream == null ? const Text("") : StreamViewTexture(_stream),
        ),
        floatingActionButton: FloatingActionButton(
          child: _recording
              ? const Icon(Icons.fiber_smart_record)
              : const Icon(Icons.not_started),
          onPressed: ()async {
            if (_recording) {
              _connection?.close();
              setState(() {
                _recording = false;
              });
            } else {
              _connection?.connect("rtmp://example.com/live");
           
            }
          },
        ),

**Comment by shogo4405** [comment]
Thank you for your message. I couldn't understand the content of your question.
I don't think we can make any progress if we continue like this, so I will stop handling this matter.
