### ISSUE TITLE
NetConnection.Connect.Rejected - code=403

### ISSUE THREAD

**Issue by Nandhu-89** [shogo4405/HaishinKit.dart#66]
### Describe the bug

I am developing a flutter application which requires two way audio and I used haishinkit to publish audio from flutter app to wowza server through RTMP. In wowza server we enabled authentication. When I tried connecting RTMP it always returns connection rejected message. In android its working we are facing issue in iOS.
Url we used => rtmp://user:pwd@domain.com:1935/applicationName/
after successful connection we will publish the audio using  streamName.
Without authentication working fine but authentication is required for our app security purpose.

### To Reproduce

Below is the error 
audio event listener {type: rtmpStatus, data: {code: NetConnection.Connect.Rejected, description: [ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ] : , level: error}}

### Expected behavior

App needs to connect with authentication.
rtmp://user:pwd@domain.com:1935/applicationName/

### Version

haishin_kit 0.13.0

### Smartphone info.

IOS Devices

### Relevant log output

```shell
audio event listener {type: rtmpStatus, data: {code: NetConnection.Connect.Rejected, description: [ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ] : , level: error}}
```

**Comment by Nandhu-89** [comment]
@shogo4405 Currently I am using haishin_kit: ^0.13.0 in my flutter app. How can I get HaishinKit 2.0.0 code. Can you please guide us to move further. because this is the issue that gating our app release.

**Comment by shogo4405** [comment]
iOS version 2.0.0 is available here. It is still in beta and currently undergoing testing.
https://github.com/shogo4405/HaishinKit.swift

**Comment by balaji-bjm** [comment]
I am new to flutter development and I'm also facing the same problem in ios. RTMP connection always returns Rejected message eventhough the url contains username and password.

**Comment by Nandhu-89** [comment]
> iOS version 2.0.0 is available here. It is still in beta and currently undergoing testing. https://github.com/shogo4405/HaishinKit.swift

Ok let me know what are all the fixes that i have to update in the flutter haishinkit sdk. Your guidance will be helpful to us @shogo4405

**Comment by shogo4405** [comment]
@Nandhu-89  No. I don't offer that kind of support. If you're looking for commercial support, I recommend finding a different product.
