### ISSUE TITLE
Missing release of bugfix

### ISSUE THREAD

**Issue by TheFe91** [shogo4405/HaishinKit.dart#9]
### Describe the bug

PR #7 fixed a critical bug. The release is still not available on pub.dev though

### To Reproduce

1. Download the latest version from pub.dev
2. Set video settings
3. Start streaming

### Expected behavior

Streaming is done in the settings provided

### Version

0.9.1

**Comment by shogo4405** [comment]
Right. I will release this weekend. Please wait. Thank you.

**Comment by shogo4405** [comment]
I released https://pub.dev/packages/haishin_kit as 0.9.2.
Thank you.
